<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace tglobally\tg_cliente\controllers;

use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;


use html\tg_cte_alianza_html;


use html\tg_sucursal_alianza_html;
use models\tg_cte_alianza;
use models\tg_sucursal_alianza;
use PDO;
use stdClass;
use tglobally\template_tg\html;

class controlador_tg_sucursal_alianza extends system {

    public function __construct(PDO $link, html $html = new \tglobally\template_tg\html(),
                                stdClass $paths_conf = new stdClass()){
        $modelo = new tg_sucursal_alianza(link: $link);
        $html_ = new tg_sucursal_alianza_html(html: $html);
        $obj_link = new links_menu($this->registro_id);
        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Sucursal Alianza';
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false, ws: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws:$ws);
        }

        $inputs = (new tg_sucursal_alianza_html(html: $this->html_base))->genera_inputs_alta(controler: $this, link: $this->link);
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al generar inputs',data:  $inputs);
            print_r($error);
            die('Error');
        }
        return $r_alta;
    }


}
